import {Inter} from "next/font/google";
import "./globals.css";
import {AuthProvider} from "@/context/AuthContext";
import Navbar from "@/components/layout/header/Navbar";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "React Lesson App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <AuthProvider>
            <html lang="en">
            <body className={inter.className}>
            <Navbar/>
            <main>
                {children}
            </main>
            </body>
            </html>
        </AuthProvider>
    );
}
